start cmd /c "go run .\cmd\component\task\main.go"
start cmd /c "go run .\cmd\component\logger\main.go"
start cmd /c "go run .\cmd\component\auth\main.go"
start cmd /c "go run .\cmd\gateway\main.go"
start cmd /c "go run .\cmd\rpc\merchandise\main.go"
start cmd /c "go run .\cmd\rpc\user\main.go"