// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: internal/proto/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 更改用户信息
type UpdatePersonalInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname     string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Introduction string `protobuf:"bytes,2,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Gender       string `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Sign         string `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *UpdatePersonalInfoReq) Reset() {
	*x = UpdatePersonalInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePersonalInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonalInfoReq) ProtoMessage() {}

func (x *UpdatePersonalInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonalInfoReq.ProtoReflect.Descriptor instead.
func (*UpdatePersonalInfoReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePersonalInfoReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdatePersonalInfoReq) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *UpdatePersonalInfoReq) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdatePersonalInfoReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type UpdatePersonalInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdatePersonalInfoResp) Reset() {
	*x = UpdatePersonalInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePersonalInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonalInfoResp) ProtoMessage() {}

func (x *UpdatePersonalInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonalInfoResp.ProtoReflect.Descriptor instead.
func (*UpdatePersonalInfoResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePersonalInfoResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePersonalInfoResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePersonalInfoResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改密码
type ModifyPasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewPassword string `protobuf:"bytes,1,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	VerifyCode  string `protobuf:"bytes,2,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
}

func (x *ModifyPasswordReq) Reset() {
	*x = ModifyPasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPasswordReq) ProtoMessage() {}

func (x *ModifyPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPasswordReq.ProtoReflect.Descriptor instead.
func (*ModifyPasswordReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *ModifyPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ModifyPasswordReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type ModifyPasswordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModifyPasswordResp) Reset() {
	*x = ModifyPasswordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPasswordResp) ProtoMessage() {}

func (x *ModifyPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPasswordResp.ProtoReflect.Descriptor instead.
func (*ModifyPasswordResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyPasswordResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ModifyPasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ModifyPasswordResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 新增收货地址
type AddReceiverAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DetailedAddress string `protobuf:"bytes,1,opt,name=detailedAddress,proto3" json:"detailedAddress,omitempty"`
	Receiver        string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Phone           string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Label           string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *AddReceiverAddressReq) Reset() {
	*x = AddReceiverAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReceiverAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReceiverAddressReq) ProtoMessage() {}

func (x *AddReceiverAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReceiverAddressReq.ProtoReflect.Descriptor instead.
func (*AddReceiverAddressReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *AddReceiverAddressReq) GetDetailedAddress() string {
	if x != nil {
		return x.DetailedAddress
	}
	return ""
}

func (x *AddReceiverAddressReq) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *AddReceiverAddressReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddReceiverAddressReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type AddReceiverAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddReceiverAddressResp) Reset() {
	*x = AddReceiverAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReceiverAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReceiverAddressResp) ProtoMessage() {}

func (x *AddReceiverAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReceiverAddressResp.ProtoReflect.Descriptor instead.
func (*AddReceiverAddressResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *AddReceiverAddressResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AddReceiverAddressResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddReceiverAddressResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除收货地址
type DeleteReceiverAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteReceiverAddressReq) Reset() {
	*x = DeleteReceiverAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReceiverAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReceiverAddressReq) ProtoMessage() {}

func (x *DeleteReceiverAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReceiverAddressReq.ProtoReflect.Descriptor instead.
func (*DeleteReceiverAddressReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReceiverAddressReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReceiverAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteReceiverAddressResp) Reset() {
	*x = DeleteReceiverAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReceiverAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReceiverAddressResp) ProtoMessage() {}

func (x *DeleteReceiverAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReceiverAddressResp.ProtoReflect.Descriptor instead.
func (*DeleteReceiverAddressResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReceiverAddressResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteReceiverAddressResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteReceiverAddressResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改收货地址
type UpdateReceiverAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DetailedAddress string `protobuf:"bytes,2,opt,name=detailedAddress,proto3" json:"detailedAddress,omitempty"`
	Receiver        string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Phone           string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Label           string `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *UpdateReceiverAddressReq) Reset() {
	*x = UpdateReceiverAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReceiverAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReceiverAddressReq) ProtoMessage() {}

func (x *UpdateReceiverAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReceiverAddressReq.ProtoReflect.Descriptor instead.
func (*UpdateReceiverAddressReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateReceiverAddressReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateReceiverAddressReq) GetDetailedAddress() string {
	if x != nil {
		return x.DetailedAddress
	}
	return ""
}

func (x *UpdateReceiverAddressReq) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *UpdateReceiverAddressReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateReceiverAddressReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type UpdateReceiverAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateReceiverAddressResp) Reset() {
	*x = UpdateReceiverAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReceiverAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReceiverAddressResp) ProtoMessage() {}

func (x *UpdateReceiverAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReceiverAddressResp.ProtoReflect.Descriptor instead.
func (*UpdateReceiverAddressResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateReceiverAddressResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateReceiverAddressResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateReceiverAddressResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 查看收货地址
type GetReceiverAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReceiverAddressReq) Reset() {
	*x = GetReceiverAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiverAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiverAddressReq) ProtoMessage() {}

func (x *GetReceiverAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiverAddressReq.ProtoReflect.Descriptor instead.
func (*GetReceiverAddressReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{10}
}

type GetReceiverAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetReceiverAddressResp) Reset() {
	*x = GetReceiverAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiverAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiverAddressResp) ProtoMessage() {}

func (x *GetReceiverAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiverAddressResp.ProtoReflect.Descriptor instead.
func (*GetReceiverAddressResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetReceiverAddressResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetReceiverAddressResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetReceiverAddressResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 收藏
type AddFavouritesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetID string `protobuf:"bytes,1,opt,name=targetID,proto3" json:"targetID,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *AddFavouritesReq) Reset() {
	*x = AddFavouritesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFavouritesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavouritesReq) ProtoMessage() {}

func (x *AddFavouritesReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavouritesReq.ProtoReflect.Descriptor instead.
func (*AddFavouritesReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *AddFavouritesReq) GetTargetID() string {
	if x != nil {
		return x.TargetID
	}
	return ""
}

func (x *AddFavouritesReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AddFavouritesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddFavouritesResp) Reset() {
	*x = AddFavouritesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFavouritesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavouritesResp) ProtoMessage() {}

func (x *AddFavouritesResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavouritesResp.ProtoReflect.Descriptor instead.
func (*AddFavouritesResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *AddFavouritesResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AddFavouritesResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddFavouritesResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 取消收藏
type DeleteFavouritesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetID string `protobuf:"bytes,1,opt,name=targetID,proto3" json:"targetID,omitempty"`
}

func (x *DeleteFavouritesReq) Reset() {
	*x = DeleteFavouritesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFavouritesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavouritesReq) ProtoMessage() {}

func (x *DeleteFavouritesReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavouritesReq.ProtoReflect.Descriptor instead.
func (*DeleteFavouritesReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFavouritesReq) GetTargetID() string {
	if x != nil {
		return x.TargetID
	}
	return ""
}

type DeleteFavouritesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteFavouritesResp) Reset() {
	*x = DeleteFavouritesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFavouritesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavouritesResp) ProtoMessage() {}

func (x *DeleteFavouritesResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavouritesResp.ProtoReflect.Descriptor instead.
func (*DeleteFavouritesResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteFavouritesResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteFavouritesResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteFavouritesResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取收藏列表
type GetFavouritesListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *GetFavouritesListReq) Reset() {
	*x = GetFavouritesListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFavouritesListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavouritesListReq) ProtoMessage() {}

func (x *GetFavouritesListReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavouritesListReq.ProtoReflect.Descriptor instead.
func (*GetFavouritesListReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetFavouritesListReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetFavouritesListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFavouritesListResp) Reset() {
	*x = GetFavouritesListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFavouritesListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavouritesListResp) ProtoMessage() {}

func (x *GetFavouritesListResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavouritesListResp.ProtoReflect.Descriptor instead.
func (*GetFavouritesListResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetFavouritesListResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetFavouritesListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFavouritesListResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 添加足迹
type AddFootprintReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetID string `protobuf:"bytes,1,opt,name=targetID,proto3" json:"targetID,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *AddFootprintReq) Reset() {
	*x = AddFootprintReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFootprintReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFootprintReq) ProtoMessage() {}

func (x *AddFootprintReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFootprintReq.ProtoReflect.Descriptor instead.
func (*AddFootprintReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *AddFootprintReq) GetTargetID() string {
	if x != nil {
		return x.TargetID
	}
	return ""
}

func (x *AddFootprintReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AddFootprintResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddFootprintResp) Reset() {
	*x = AddFootprintResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFootprintResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFootprintResp) ProtoMessage() {}

func (x *AddFootprintResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFootprintResp.ProtoReflect.Descriptor instead.
func (*AddFootprintResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *AddFootprintResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AddFootprintResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddFootprintResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除足迹
type DeleteFootprintReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetID string `protobuf:"bytes,1,opt,name=targetID,proto3" json:"targetID,omitempty"`
}

func (x *DeleteFootprintReq) Reset() {
	*x = DeleteFootprintReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFootprintReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFootprintReq) ProtoMessage() {}

func (x *DeleteFootprintReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFootprintReq.ProtoReflect.Descriptor instead.
func (*DeleteFootprintReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteFootprintReq) GetTargetID() string {
	if x != nil {
		return x.TargetID
	}
	return ""
}

type DeleteFootprintResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteFootprintResp) Reset() {
	*x = DeleteFootprintResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFootprintResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFootprintResp) ProtoMessage() {}

func (x *DeleteFootprintResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFootprintResp.ProtoReflect.Descriptor instead.
func (*DeleteFootprintResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteFootprintResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteFootprintResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteFootprintResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 查看足迹
type GetFootprintListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *GetFootprintListReq) Reset() {
	*x = GetFootprintListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFootprintListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFootprintListReq) ProtoMessage() {}

func (x *GetFootprintListReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFootprintListReq.ProtoReflect.Descriptor instead.
func (*GetFootprintListReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetFootprintListReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetFootprintListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFootprintListResp) Reset() {
	*x = GetFootprintListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFootprintListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFootprintListResp) ProtoMessage() {}

func (x *GetFootprintListResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFootprintListResp.ProtoReflect.Descriptor instead.
func (*GetFootprintListResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{23}
}

func (x *GetFootprintListResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetFootprintListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFootprintListResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 关注
type FollowMerchantReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantID string `protobuf:"bytes,1,opt,name=merchantID,proto3" json:"merchantID,omitempty"`
}

func (x *FollowMerchantReq) Reset() {
	*x = FollowMerchantReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowMerchantReq) ProtoMessage() {}

func (x *FollowMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowMerchantReq.ProtoReflect.Descriptor instead.
func (*FollowMerchantReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{24}
}

func (x *FollowMerchantReq) GetMerchantID() string {
	if x != nil {
		return x.MerchantID
	}
	return ""
}

type FollowMerchantResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FollowMerchantResp) Reset() {
	*x = FollowMerchantResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowMerchantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowMerchantResp) ProtoMessage() {}

func (x *FollowMerchantResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowMerchantResp.ProtoReflect.Descriptor instead.
func (*FollowMerchantResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{25}
}

func (x *FollowMerchantResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FollowMerchantResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FollowMerchantResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 取关
type CancelFollowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantID string `protobuf:"bytes,1,opt,name=merchantID,proto3" json:"merchantID,omitempty"`
}

func (x *CancelFollowReq) Reset() {
	*x = CancelFollowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFollowReq) ProtoMessage() {}

func (x *CancelFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFollowReq.ProtoReflect.Descriptor instead.
func (*CancelFollowReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{26}
}

func (x *CancelFollowReq) GetMerchantID() string {
	if x != nil {
		return x.MerchantID
	}
	return ""
}

type CancelFollowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CancelFollowResp) Reset() {
	*x = CancelFollowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelFollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFollowResp) ProtoMessage() {}

func (x *CancelFollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFollowResp.ProtoReflect.Descriptor instead.
func (*CancelFollowResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{27}
}

func (x *CancelFollowResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CancelFollowResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelFollowResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 查看关注列表
type GetFollowListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFollowListReq) Reset() {
	*x = GetFollowListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFollowListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListReq) ProtoMessage() {}

func (x *GetFollowListReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListReq.ProtoReflect.Descriptor instead.
func (*GetFollowListReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{28}
}

type GetFollowListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFollowListResp) Reset() {
	*x = GetFollowListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_user_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFollowListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListResp) ProtoMessage() {}

func (x *GetFollowListResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListResp.ProtoReflect.Descriptor instead.
func (*GetFollowListResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_proto_rawDescGZIP(), []int{29}
}

func (x *GetFollowListResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetFollowListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFollowListResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_proto_user_proto protoreflect.FileDescriptor

var file_internal_proto_user_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x83, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x5a,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x11, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x20, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x56, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x89, 0x01, 0x0a, 0x15, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x0f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x5a, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5d, 0x0a,
	0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9c, 0x01, 0x0a,
	0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x5d, 0x0a, 0x19, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x22, 0x5a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x4a, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x55, 0x0a, 0x11, 0x41,
	0x64, 0x64, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x31, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f,
	0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x49, 0x44, 0x22, 0x58, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x22, 0x59, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72,
	0x69, 0x74, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x49,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x54, 0x0a, 0x10, 0x41, 0x64, 0x64,
	0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x30, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49,
	0x44, 0x22, 0x57, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x74, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x58, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x11, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a,
	0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x56, 0x0a, 0x12,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x0f, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x54, 0x0a, 0x10, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x12, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x22, 0x55, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xbe, 0x0a, 0x0a, 0x0b, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x1a, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x12, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x66, 0x0a, 0x15, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x66, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x46,
	0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x61, 0x76, 0x6f, 0x75,
	0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72,
	0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x57, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x21,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x5a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75,
	0x72, 0x69, 0x74, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a,
	0x0c, 0x41, 0x64, 0x64, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x46,
	0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x6f, 0x6f,
	0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x54, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x0e, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x0c,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x1c, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_user_proto_rawDescOnce sync.Once
	file_internal_proto_user_proto_rawDescData = file_internal_proto_user_proto_rawDesc
)

func file_internal_proto_user_proto_rawDescGZIP() []byte {
	file_internal_proto_user_proto_rawDescOnce.Do(func() {
		file_internal_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_user_proto_rawDescData)
	})
	return file_internal_proto_user_proto_rawDescData
}

var file_internal_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_internal_proto_user_proto_goTypes = []any{
	(*UpdatePersonalInfoReq)(nil),     // 0: user_master.UpdatePersonalInfoReq
	(*UpdatePersonalInfoResp)(nil),    // 1: user_master.UpdatePersonalInfoResp
	(*ModifyPasswordReq)(nil),         // 2: user_master.ModifyPasswordReq
	(*ModifyPasswordResp)(nil),        // 3: user_master.ModifyPasswordResp
	(*AddReceiverAddressReq)(nil),     // 4: user_master.AddReceiverAddressReq
	(*AddReceiverAddressResp)(nil),    // 5: user_master.AddReceiverAddressResp
	(*DeleteReceiverAddressReq)(nil),  // 6: user_master.DeleteReceiverAddressReq
	(*DeleteReceiverAddressResp)(nil), // 7: user_master.DeleteReceiverAddressResp
	(*UpdateReceiverAddressReq)(nil),  // 8: user_master.UpdateReceiverAddressReq
	(*UpdateReceiverAddressResp)(nil), // 9: user_master.UpdateReceiverAddressResp
	(*GetReceiverAddressReq)(nil),     // 10: user_master.GetReceiverAddressReq
	(*GetReceiverAddressResp)(nil),    // 11: user_master.GetReceiverAddressResp
	(*AddFavouritesReq)(nil),          // 12: user_master.AddFavouritesReq
	(*AddFavouritesResp)(nil),         // 13: user_master.AddFavouritesResp
	(*DeleteFavouritesReq)(nil),       // 14: user_master.DeleteFavouritesReq
	(*DeleteFavouritesResp)(nil),      // 15: user_master.DeleteFavouritesResp
	(*GetFavouritesListReq)(nil),      // 16: user_master.GetFavouritesListReq
	(*GetFavouritesListResp)(nil),     // 17: user_master.GetFavouritesListResp
	(*AddFootprintReq)(nil),           // 18: user_master.AddFootprintReq
	(*AddFootprintResp)(nil),          // 19: user_master.AddFootprintResp
	(*DeleteFootprintReq)(nil),        // 20: user_master.DeleteFootprintReq
	(*DeleteFootprintResp)(nil),       // 21: user_master.DeleteFootprintResp
	(*GetFootprintListReq)(nil),       // 22: user_master.GetFootprintListReq
	(*GetFootprintListResp)(nil),      // 23: user_master.GetFootprintListResp
	(*FollowMerchantReq)(nil),         // 24: user_master.FollowMerchantReq
	(*FollowMerchantResp)(nil),        // 25: user_master.FollowMerchantResp
	(*CancelFollowReq)(nil),           // 26: user_master.CancelFollowReq
	(*CancelFollowResp)(nil),          // 27: user_master.CancelFollowResp
	(*GetFollowListReq)(nil),          // 28: user_master.GetFollowListReq
	(*GetFollowListResp)(nil),         // 29: user_master.GetFollowListResp
}
var file_internal_proto_user_proto_depIdxs = []int32{
	0,  // 0: user_master.UserService.UpdatePersonalInfo:input_type -> user_master.UpdatePersonalInfoReq
	2,  // 1: user_master.UserService.ModifyPassword:input_type -> user_master.ModifyPasswordReq
	4,  // 2: user_master.UserService.AddReceiverAddress:input_type -> user_master.AddReceiverAddressReq
	6,  // 3: user_master.UserService.DeleteReceiverAddress:input_type -> user_master.DeleteReceiverAddressReq
	8,  // 4: user_master.UserService.UpdateReceiverAddress:input_type -> user_master.UpdateReceiverAddressReq
	10, // 5: user_master.UserService.GetReceiverAddress:input_type -> user_master.GetReceiverAddressReq
	12, // 6: user_master.UserService.AddFavourites:input_type -> user_master.AddFavouritesReq
	14, // 7: user_master.UserService.DeleteFavourites:input_type -> user_master.DeleteFavouritesReq
	16, // 8: user_master.UserService.GetFavouritesList:input_type -> user_master.GetFavouritesListReq
	18, // 9: user_master.UserService.AddFootprint:input_type -> user_master.AddFootprintReq
	20, // 10: user_master.UserService.DeleteFootprint:input_type -> user_master.DeleteFootprintReq
	22, // 11: user_master.UserService.GetFootprintList:input_type -> user_master.GetFootprintListReq
	24, // 12: user_master.UserService.FollowMerchant:input_type -> user_master.FollowMerchantReq
	26, // 13: user_master.UserService.CancelFollow:input_type -> user_master.CancelFollowReq
	28, // 14: user_master.UserService.GetFollowList:input_type -> user_master.GetFollowListReq
	1,  // 15: user_master.UserService.UpdatePersonalInfo:output_type -> user_master.UpdatePersonalInfoResp
	3,  // 16: user_master.UserService.ModifyPassword:output_type -> user_master.ModifyPasswordResp
	5,  // 17: user_master.UserService.AddReceiverAddress:output_type -> user_master.AddReceiverAddressResp
	7,  // 18: user_master.UserService.DeleteReceiverAddress:output_type -> user_master.DeleteReceiverAddressResp
	9,  // 19: user_master.UserService.UpdateReceiverAddress:output_type -> user_master.UpdateReceiverAddressResp
	11, // 20: user_master.UserService.GetReceiverAddress:output_type -> user_master.GetReceiverAddressResp
	13, // 21: user_master.UserService.AddFavourites:output_type -> user_master.AddFavouritesResp
	15, // 22: user_master.UserService.DeleteFavourites:output_type -> user_master.DeleteFavouritesResp
	17, // 23: user_master.UserService.GetFavouritesList:output_type -> user_master.GetFavouritesListResp
	19, // 24: user_master.UserService.AddFootprint:output_type -> user_master.AddFootprintResp
	21, // 25: user_master.UserService.DeleteFootprint:output_type -> user_master.DeleteFootprintResp
	23, // 26: user_master.UserService.GetFootprintList:output_type -> user_master.GetFootprintListResp
	25, // 27: user_master.UserService.FollowMerchant:output_type -> user_master.FollowMerchantResp
	27, // 28: user_master.UserService.CancelFollow:output_type -> user_master.CancelFollowResp
	29, // 29: user_master.UserService.GetFollowList:output_type -> user_master.GetFollowListResp
	15, // [15:30] is the sub-list for method output_type
	0,  // [0:15] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_user_proto_init() }
func file_internal_proto_user_proto_init() {
	if File_internal_proto_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_user_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePersonalInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePersonalInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ModifyPasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ModifyPasswordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AddReceiverAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AddReceiverAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReceiverAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReceiverAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateReceiverAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateReceiverAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetReceiverAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetReceiverAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AddFavouritesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AddFavouritesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFavouritesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFavouritesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetFavouritesListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetFavouritesListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*AddFootprintReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*AddFootprintResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFootprintReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFootprintResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*GetFootprintListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*GetFootprintListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*FollowMerchantReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*FollowMerchantResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*CancelFollowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*CancelFollowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*GetFollowListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_user_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*GetFollowListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_user_proto_goTypes,
		DependencyIndexes: file_internal_proto_user_proto_depIdxs,
		MessageInfos:      file_internal_proto_user_proto_msgTypes,
	}.Build()
	File_internal_proto_user_proto = out.File
	file_internal_proto_user_proto_rawDesc = nil
	file_internal_proto_user_proto_goTypes = nil
	file_internal_proto_user_proto_depIdxs = nil
}
