redis:
  addr: "10.3.0.42"
  port: "6379"
  password: ""
mysql:
  addr: "127.0.0.1"
  port: "3306"
  password: "040824"
  database: "store"
  name: "root"
  conf: "charset=utf8&parseTime=true&loc=Local"
consul:
  addr: "10.3.0.42"
  port: "8500"
  name: "merchandise"
kafka:
  addr: "10.3.0.42"
  port: "9092"
logger:
  maxSize: 1
  maxAge: 1
  maxBackUps: 1
secretKey: "qingqing"
mongoDB:
  address: "127.0.0.1"
  port: "27017"
  database: "chat"
email:
  username: "1457800511@qq.com"
  password: "mpfbwsxwakbbfgdg"
  host: "smtp.qq.com"
  port: 587
minio:
  endPoint: "10.3.0.42"
  port: "9000"
  accessKey: "pSEpJE3Fz5OOcJAJTbJF"
  secretKey: "R4569RpFC0E1adcLWP4tJL20t5GZBEOiolMON4oL"
jwt:
  secretKey: "qingqing"
  accessExpiry: 1
  refreshExpiry: 3
elasticsearch:
  addr: "http://10.3.0.42"
  port: "9200"