// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: internal/proto/merchandise.proto

package merchandise

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutAwayMerchandiseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Info        string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	PictureList []string `protobuf:"bytes,3,rep,name=pictureList,proto3" json:"pictureList,omitempty"`
	Delivery    string   `protobuf:"bytes,4,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Category    string   `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *PutAwayMerchandiseReq) Reset() {
	*x = PutAwayMerchandiseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutAwayMerchandiseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAwayMerchandiseReq) ProtoMessage() {}

func (x *PutAwayMerchandiseReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAwayMerchandiseReq.ProtoReflect.Descriptor instead.
func (*PutAwayMerchandiseReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{0}
}

func (x *PutAwayMerchandiseReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutAwayMerchandiseReq) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *PutAwayMerchandiseReq) GetPictureList() []string {
	if x != nil {
		return x.PictureList
	}
	return nil
}

func (x *PutAwayMerchandiseReq) GetDelivery() string {
	if x != nil {
		return x.Delivery
	}
	return ""
}

func (x *PutAwayMerchandiseReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type PutAwayMerchandiseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PutAwayMerchandiseResp) Reset() {
	*x = PutAwayMerchandiseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutAwayMerchandiseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAwayMerchandiseResp) ProtoMessage() {}

func (x *PutAwayMerchandiseResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAwayMerchandiseResp.ProtoReflect.Descriptor instead.
func (*PutAwayMerchandiseResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{1}
}

func (x *PutAwayMerchandiseResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PutAwayMerchandiseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PutAwayMerchandiseResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RemoveMerchandiseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveMerchandiseReq) Reset() {
	*x = RemoveMerchandiseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMerchandiseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMerchandiseReq) ProtoMessage() {}

func (x *RemoveMerchandiseReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMerchandiseReq.ProtoReflect.Descriptor instead.
func (*RemoveMerchandiseReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveMerchandiseReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveMerchandiseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RemoveMerchandiseResp) Reset() {
	*x = RemoveMerchandiseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMerchandiseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMerchandiseResp) ProtoMessage() {}

func (x *RemoveMerchandiseResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMerchandiseResp.ProtoReflect.Descriptor instead.
func (*RemoveMerchandiseResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveMerchandiseResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RemoveMerchandiseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveMerchandiseResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateMerchandiseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Info        string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	PictureList []string `protobuf:"bytes,4,rep,name=pictureList,proto3" json:"pictureList,omitempty"`
	Delivery    string   `protobuf:"bytes,5,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Category    string   `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *UpdateMerchandiseReq) Reset() {
	*x = UpdateMerchandiseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMerchandiseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchandiseReq) ProtoMessage() {}

func (x *UpdateMerchandiseReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchandiseReq.ProtoReflect.Descriptor instead.
func (*UpdateMerchandiseReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMerchandiseReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMerchandiseReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMerchandiseReq) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *UpdateMerchandiseReq) GetPictureList() []string {
	if x != nil {
		return x.PictureList
	}
	return nil
}

func (x *UpdateMerchandiseReq) GetDelivery() string {
	if x != nil {
		return x.Delivery
	}
	return ""
}

func (x *UpdateMerchandiseReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateMerchandiseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateMerchandiseResp) Reset() {
	*x = UpdateMerchandiseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMerchandiseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchandiseResp) ProtoMessage() {}

func (x *UpdateMerchandiseResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchandiseResp.ProtoReflect.Descriptor instead.
func (*UpdateMerchandiseResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMerchandiseResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateMerchandiseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateMerchandiseResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMerchandiseDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMerchandiseDetailsReq) Reset() {
	*x = GetMerchandiseDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMerchandiseDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchandiseDetailsReq) ProtoMessage() {}

func (x *GetMerchandiseDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchandiseDetailsReq.ProtoReflect.Descriptor instead.
func (*GetMerchandiseDetailsReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{6}
}

func (x *GetMerchandiseDetailsReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMerchandiseDetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMerchandiseDetailsResp) Reset() {
	*x = GetMerchandiseDetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMerchandiseDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchandiseDetailsResp) ProtoMessage() {}

func (x *GetMerchandiseDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchandiseDetailsResp.ProtoReflect.Descriptor instead.
func (*GetMerchandiseDetailsResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{7}
}

func (x *GetMerchandiseDetailsResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetMerchandiseDetailsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMerchandiseDetailsResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Time    int32  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Sales   int32  `protobuf:"varint,3,opt,name=sales,proto3" json:"sales,omitempty"`
	Req     int32  `protobuf:"varint,4,opt,name=req,proto3" json:"req,omitempty"`
	Size    int32  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{8}
}

func (x *SearchReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchReq) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SearchReq) GetSales() int32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *SearchReq) GetReq() int32 {
	if x != nil {
		return x.Req
	}
	return 0
}

func (x *SearchReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{9}
}

func (x *SearchResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SearchResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchByCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Time     int32  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Sales    int32  `protobuf:"varint,3,opt,name=sales,proto3" json:"sales,omitempty"`
	Req      int32  `protobuf:"varint,4,opt,name=req,proto3" json:"req,omitempty"`
	Size     int32  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SearchByCategoryReq) Reset() {
	*x = SearchByCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByCategoryReq) ProtoMessage() {}

func (x *SearchByCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByCategoryReq.ProtoReflect.Descriptor instead.
func (*SearchByCategoryReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{10}
}

func (x *SearchByCategoryReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchByCategoryReq) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SearchByCategoryReq) GetSales() int32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *SearchByCategoryReq) GetReq() int32 {
	if x != nil {
		return x.Req
	}
	return 0
}

func (x *SearchByCategoryReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchByCategoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SearchByCategoryResp) Reset() {
	*x = SearchByCategoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByCategoryResp) ProtoMessage() {}

func (x *SearchByCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByCategoryResp.ProtoReflect.Descriptor instead.
func (*SearchByCategoryResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{11}
}

func (x *SearchByCategoryResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SearchByCategoryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchByCategoryResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddMerchandiseStyleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchandiseID string  `protobuf:"bytes,1,opt,name=merchandiseID,proto3" json:"merchandiseID,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Info          string  `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Picture       string  `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	Price         float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         uint32  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        string  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddMerchandiseStyleReq) Reset() {
	*x = AddMerchandiseStyleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMerchandiseStyleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMerchandiseStyleReq) ProtoMessage() {}

func (x *AddMerchandiseStyleReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMerchandiseStyleReq.ProtoReflect.Descriptor instead.
func (*AddMerchandiseStyleReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{12}
}

func (x *AddMerchandiseStyleReq) GetMerchandiseID() string {
	if x != nil {
		return x.MerchandiseID
	}
	return ""
}

func (x *AddMerchandiseStyleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMerchandiseStyleReq) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *AddMerchandiseStyleReq) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *AddMerchandiseStyleReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddMerchandiseStyleReq) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddMerchandiseStyleReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddMerchandiseStyleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddMerchandiseStyleResp) Reset() {
	*x = AddMerchandiseStyleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMerchandiseStyleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMerchandiseStyleResp) ProtoMessage() {}

func (x *AddMerchandiseStyleResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMerchandiseStyleResp.ProtoReflect.Descriptor instead.
func (*AddMerchandiseStyleResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{13}
}

func (x *AddMerchandiseStyleResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AddMerchandiseStyleResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddMerchandiseStyleResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RemoveMerchandiseStyleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveMerchandiseStyleReq) Reset() {
	*x = RemoveMerchandiseStyleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMerchandiseStyleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMerchandiseStyleReq) ProtoMessage() {}

func (x *RemoveMerchandiseStyleReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMerchandiseStyleReq.ProtoReflect.Descriptor instead.
func (*RemoveMerchandiseStyleReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveMerchandiseStyleReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveMerchandiseStyleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RemoveMerchandiseStyleResp) Reset() {
	*x = RemoveMerchandiseStyleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMerchandiseStyleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMerchandiseStyleResp) ProtoMessage() {}

func (x *RemoveMerchandiseStyleResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMerchandiseStyleResp.ProtoReflect.Descriptor instead.
func (*RemoveMerchandiseStyleResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveMerchandiseStyleResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RemoveMerchandiseStyleResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveMerchandiseStyleResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateMerchandiseStyleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Info    string  `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Picture string  `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	Price   float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock   int32   `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Status  string  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateMerchandiseStyleReq) Reset() {
	*x = UpdateMerchandiseStyleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMerchandiseStyleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchandiseStyleReq) ProtoMessage() {}

func (x *UpdateMerchandiseStyleReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchandiseStyleReq.ProtoReflect.Descriptor instead.
func (*UpdateMerchandiseStyleReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateMerchandiseStyleReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMerchandiseStyleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMerchandiseStyleReq) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *UpdateMerchandiseStyleReq) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *UpdateMerchandiseStyleReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateMerchandiseStyleReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateMerchandiseStyleReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateMerchandiseStyleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateMerchandiseStyleResp) Reset() {
	*x = UpdateMerchandiseStyleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMerchandiseStyleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchandiseStyleResp) ProtoMessage() {}

func (x *UpdateMerchandiseStyleResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchandiseStyleResp.ProtoReflect.Descriptor instead.
func (*UpdateMerchandiseStyleResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMerchandiseStyleResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateMerchandiseStyleResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateMerchandiseStyleResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMerchandiseStyleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchandiseID string `protobuf:"bytes,1,opt,name=merchandiseID,proto3" json:"merchandiseID,omitempty"`
	Req           int32  `protobuf:"varint,4,opt,name=req,proto3" json:"req,omitempty"`
	Size          int32  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *GetMerchandiseStyleListReq) Reset() {
	*x = GetMerchandiseStyleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMerchandiseStyleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchandiseStyleListReq) ProtoMessage() {}

func (x *GetMerchandiseStyleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchandiseStyleListReq.ProtoReflect.Descriptor instead.
func (*GetMerchandiseStyleListReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{18}
}

func (x *GetMerchandiseStyleListReq) GetMerchandiseID() string {
	if x != nil {
		return x.MerchandiseID
	}
	return ""
}

func (x *GetMerchandiseStyleListReq) GetReq() int32 {
	if x != nil {
		return x.Req
	}
	return 0
}

func (x *GetMerchandiseStyleListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetMerchandiseStyleListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMerchandiseStyleListResp) Reset() {
	*x = GetMerchandiseStyleListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMerchandiseStyleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchandiseStyleListResp) ProtoMessage() {}

func (x *GetMerchandiseStyleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchandiseStyleListResp.ProtoReflect.Descriptor instead.
func (*GetMerchandiseStyleListResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{19}
}

func (x *GetMerchandiseStyleListResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetMerchandiseStyleListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMerchandiseStyleListResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMerchandiseStyleDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMerchandiseStyleDetailsReq) Reset() {
	*x = GetMerchandiseStyleDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMerchandiseStyleDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchandiseStyleDetailsReq) ProtoMessage() {}

func (x *GetMerchandiseStyleDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchandiseStyleDetailsReq.ProtoReflect.Descriptor instead.
func (*GetMerchandiseStyleDetailsReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{20}
}

func (x *GetMerchandiseStyleDetailsReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMerchandiseStyleDetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMerchandiseStyleDetailsResp) Reset() {
	*x = GetMerchandiseStyleDetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_merchandise_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMerchandiseStyleDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchandiseStyleDetailsResp) ProtoMessage() {}

func (x *GetMerchandiseStyleDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_merchandise_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchandiseStyleDetailsResp.ProtoReflect.Descriptor instead.
func (*GetMerchandiseStyleDetailsResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_merchandise_proto_rawDescGZIP(), []int{21}
}

func (x *GetMerchandiseStyleDetailsResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetMerchandiseStyleDetailsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMerchandiseStyleDetailsResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_proto_merchandise_proto protoreflect.FileDescriptor

var file_internal_proto_merchandise_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x99, 0x01, 0x0a, 0x15, 0x50, 0x75, 0x74, 0x41, 0x77, 0x61, 0x79, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x5a, 0x0a,
	0x16, 0x50, 0x75, 0x74, 0x41, 0x77, 0x61, 0x79, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64,
	0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x59, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa8, 0x01, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x59, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x64, 0x69, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5d,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x75, 0x0a,
	0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x4e, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42,
	0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x61, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x61, 0x6c,
	0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x58, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xc4, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a,
	0x0d, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73,
	0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5b, 0x0a, 0x17, 0x41, 0x64, 0x64,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xb1, 0x01, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5e, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x64, 0x69, 0x73, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x22, 0x5f, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64,
	0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x2f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x62, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xf0, 0x08, 0x0a, 0x12, 0x4d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61,
	0x0a, 0x12, 0x50, 0x75, 0x74, 0x41, 0x77, 0x61, 0x79, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x64, 0x69, 0x73, 0x65, 0x12, 0x24, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x41, 0x77, 0x61, 0x79, 0x4d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x41, 0x77,
	0x61, 0x79, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x5e, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x12, 0x23, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x5e, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x12, 0x23, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x6a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64,
	0x69, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x27, 0x2e, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69,
	0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a,
	0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x18, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5b, 0x0a, 0x10,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x22, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x64, 0x0a, 0x13, 0x41, 0x64, 0x64,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65,
	0x12, 0x25, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53,
	0x74, 0x79, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x6d, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x28, 0x2e, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x6d,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64,
	0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x28, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x29, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x70, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53,
	0x74, 0x79, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69,
	0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x79, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73,
	0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2c, 0x2e,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x2d, 0x2e, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x1e, 0x5a, 0x1c, 0x2e, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_proto_merchandise_proto_rawDescOnce sync.Once
	file_internal_proto_merchandise_proto_rawDescData = file_internal_proto_merchandise_proto_rawDesc
)

func file_internal_proto_merchandise_proto_rawDescGZIP() []byte {
	file_internal_proto_merchandise_proto_rawDescOnce.Do(func() {
		file_internal_proto_merchandise_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_merchandise_proto_rawDescData)
	})
	return file_internal_proto_merchandise_proto_rawDescData
}

var file_internal_proto_merchandise_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_proto_merchandise_proto_goTypes = []any{
	(*PutAwayMerchandiseReq)(nil),          // 0: friend_master.PutAwayMerchandiseReq
	(*PutAwayMerchandiseResp)(nil),         // 1: friend_master.PutAwayMerchandiseResp
	(*RemoveMerchandiseReq)(nil),           // 2: friend_master.RemoveMerchandiseReq
	(*RemoveMerchandiseResp)(nil),          // 3: friend_master.RemoveMerchandiseResp
	(*UpdateMerchandiseReq)(nil),           // 4: friend_master.UpdateMerchandiseReq
	(*UpdateMerchandiseResp)(nil),          // 5: friend_master.UpdateMerchandiseResp
	(*GetMerchandiseDetailsReq)(nil),       // 6: friend_master.GetMerchandiseDetailsReq
	(*GetMerchandiseDetailsResp)(nil),      // 7: friend_master.GetMerchandiseDetailsResp
	(*SearchReq)(nil),                      // 8: friend_master.SearchReq
	(*SearchResp)(nil),                     // 9: friend_master.SearchResp
	(*SearchByCategoryReq)(nil),            // 10: friend_master.SearchByCategoryReq
	(*SearchByCategoryResp)(nil),           // 11: friend_master.SearchByCategoryResp
	(*AddMerchandiseStyleReq)(nil),         // 12: friend_master.AddMerchandiseStyleReq
	(*AddMerchandiseStyleResp)(nil),        // 13: friend_master.AddMerchandiseStyleResp
	(*RemoveMerchandiseStyleReq)(nil),      // 14: friend_master.RemoveMerchandiseStyleReq
	(*RemoveMerchandiseStyleResp)(nil),     // 15: friend_master.RemoveMerchandiseStyleResp
	(*UpdateMerchandiseStyleReq)(nil),      // 16: friend_master.UpdateMerchandiseStyleReq
	(*UpdateMerchandiseStyleResp)(nil),     // 17: friend_master.UpdateMerchandiseStyleResp
	(*GetMerchandiseStyleListReq)(nil),     // 18: friend_master.GetMerchandiseStyleListReq
	(*GetMerchandiseStyleListResp)(nil),    // 19: friend_master.GetMerchandiseStyleListResp
	(*GetMerchandiseStyleDetailsReq)(nil),  // 20: friend_master.GetMerchandiseStyleDetailsReq
	(*GetMerchandiseStyleDetailsResp)(nil), // 21: friend_master.GetMerchandiseStyleDetailsResp
}
var file_internal_proto_merchandise_proto_depIdxs = []int32{
	0,  // 0: friend_master.MerchandiseService.PutAwayMerchandise:input_type -> friend_master.PutAwayMerchandiseReq
	2,  // 1: friend_master.MerchandiseService.RemoveMerchandise:input_type -> friend_master.RemoveMerchandiseReq
	4,  // 2: friend_master.MerchandiseService.UpdateMerchandise:input_type -> friend_master.UpdateMerchandiseReq
	6,  // 3: friend_master.MerchandiseService.GetMerchandiseDetails:input_type -> friend_master.GetMerchandiseDetailsReq
	8,  // 4: friend_master.MerchandiseService.Search:input_type -> friend_master.SearchReq
	10, // 5: friend_master.MerchandiseService.SearchByCategory:input_type -> friend_master.SearchByCategoryReq
	12, // 6: friend_master.MerchandiseService.AddMerchandiseStyle:input_type -> friend_master.AddMerchandiseStyleReq
	14, // 7: friend_master.MerchandiseService.RemoveMerchandiseStyle:input_type -> friend_master.RemoveMerchandiseStyleReq
	16, // 8: friend_master.MerchandiseService.UpdateMerchandiseStyle:input_type -> friend_master.UpdateMerchandiseStyleReq
	18, // 9: friend_master.MerchandiseService.GetMerchandiseStyleList:input_type -> friend_master.GetMerchandiseStyleListReq
	20, // 10: friend_master.MerchandiseService.GetMerchandiseStyleDetails:input_type -> friend_master.GetMerchandiseStyleDetailsReq
	1,  // 11: friend_master.MerchandiseService.PutAwayMerchandise:output_type -> friend_master.PutAwayMerchandiseResp
	3,  // 12: friend_master.MerchandiseService.RemoveMerchandise:output_type -> friend_master.RemoveMerchandiseResp
	5,  // 13: friend_master.MerchandiseService.UpdateMerchandise:output_type -> friend_master.UpdateMerchandiseResp
	7,  // 14: friend_master.MerchandiseService.GetMerchandiseDetails:output_type -> friend_master.GetMerchandiseDetailsResp
	9,  // 15: friend_master.MerchandiseService.Search:output_type -> friend_master.SearchResp
	11, // 16: friend_master.MerchandiseService.SearchByCategory:output_type -> friend_master.SearchByCategoryResp
	13, // 17: friend_master.MerchandiseService.AddMerchandiseStyle:output_type -> friend_master.AddMerchandiseStyleResp
	15, // 18: friend_master.MerchandiseService.RemoveMerchandiseStyle:output_type -> friend_master.RemoveMerchandiseStyleResp
	17, // 19: friend_master.MerchandiseService.UpdateMerchandiseStyle:output_type -> friend_master.UpdateMerchandiseStyleResp
	19, // 20: friend_master.MerchandiseService.GetMerchandiseStyleList:output_type -> friend_master.GetMerchandiseStyleListResp
	21, // 21: friend_master.MerchandiseService.GetMerchandiseStyleDetails:output_type -> friend_master.GetMerchandiseStyleDetailsResp
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_merchandise_proto_init() }
func file_internal_proto_merchandise_proto_init() {
	if File_internal_proto_merchandise_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_merchandise_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PutAwayMerchandiseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PutAwayMerchandiseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMerchandiseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMerchandiseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMerchandiseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMerchandiseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetMerchandiseDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetMerchandiseDetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SearchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SearchByCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SearchByCategoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AddMerchandiseStyleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AddMerchandiseStyleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMerchandiseStyleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMerchandiseStyleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMerchandiseStyleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMerchandiseStyleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetMerchandiseStyleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetMerchandiseStyleListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*GetMerchandiseStyleDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_merchandise_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*GetMerchandiseStyleDetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_merchandise_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_merchandise_proto_goTypes,
		DependencyIndexes: file_internal_proto_merchandise_proto_depIdxs,
		MessageInfos:      file_internal_proto_merchandise_proto_msgTypes,
	}.Build()
	File_internal_proto_merchandise_proto = out.File
	file_internal_proto_merchandise_proto_rawDesc = nil
	file_internal_proto_merchandise_proto_goTypes = nil
	file_internal_proto_merchandise_proto_depIdxs = nil
}
